export const QUOTE_STATUS = {
	OPEN: 'OPEN',
	SENT: 'SENT',
	EXPIRED: 'EXPIRED',
	CONFIRMED: 'CONFIRMED',
	COMPLETED: 'COMPLETED',
	DECLINED: 'DECLINED',
	CANCELLED: 'CANCELLED',
	CONCEPT: 'CONCEPT',
} as const;
